sudo: required
services:
  - docker

before_install:
  - docker build -t irinaionescu/react-test -f ./client/Dockerfile.dev ./client
  #-f to use custom Dockerfile; build context is ./client

scripts:
  - docker run -e CI=true irinaionescu/react-test npm test --watchAll=false


after_success:
  - docker build -t irinaionescu/multi-client ./client
  - docker build -t irinaionescu/multi-nginx ./nginx
  - docker build -t irinaionescu/multi-server ./server
  - docker build -t irinaionescu/multi-worker ./worker
  #login to docker CLI (set up env variables on travis)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  #take these images and push them to dockerhub
  - docker push irinaionescu/multi-client
  - docker push irinaionescu/multi-nginx
  - docker push irinaionescu/multi-server
  - docker push irinaionescu/multi-worker




